### PR TITLE
code pull for review

### PR DESCRIPTION
**Pull request by kamranahmad123**
1 - This project perform addition, deletion and completion of tasks

### CODE REVIEW

**Comment by EnixWord** [comment]
### **The following observations were made on my partner's code**

- [ ] I commend the great effort you put inot write this great code. However, Instead of "y" it will be great to use a proper name for this variable that can manifest it's true usage.
  https://github.com/kamranahmad123/To-Do-Structure/blob/50bc48ba3baf8f0ed63e0c2eceec418dabd63b70/src/completionStatus.js#L3

- [ ] I kindly suggest instead of repeating The local storage operation three time it is better to put it in the function and call it wherever it is needed . This will make your code more clean and more profesional.
  https://github.com/kamranahmad123/To-Do-Structure/blob/50bc48ba3baf8f0ed63e0c2eceec418dabd63b70/src/newFunctionalities.js#L9

**Comment by EnixWord** [comment]
You have done a great job, and applied the changes correctly so your project is approved and now it is time to merge it.
🥇

**Comment by kamranahmad123** [comment]
> You have done a great job, and applied the changes correctly so your project is approved and now it is time to merge it. 🥇

Thanks for your time to review my code, you passed the right comments.

Thanks

**Review by EnixWord — APPROVED** [review]
You have done a great job, and applied the changes correctly so your project is approved and now it is time to merge it.
🥇

**Pull request merged**
